---
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-slave
spec:
  containers:
  - name: builder
    image: "066141165427.dkr.ecr.ap-southeast-1.amazonaws.com/jenkins/go-agent:1.13"
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1000m
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
