---
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins-slave
spec:
  tolerations:
  - effect: NoExecute
    key: jenkins
    operator: Equal
    value: none
  - effect: NoSchedule
    key: node-role.kubernetes.io/jenkins
    operator: Exists
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-role.kubernetes.io/jenkins
            operator: In
            values:
            - ""
  containers:
  - name: builder
    image: "066141165427.dkr.ecr.ap-southeast-1.amazonaws.com/jenkins/go-agent:1.17-2022-15"
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: 1000m
        memory: 1000Mi
      limits:
        cpu: 3000m
    volumeMounts:
      - name: dockersock
        mountPath: "/var/run/docker.sock"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
